services:
  # Strapi CMS
  cms:
    container_name: 3dbyte-cms
    build:
      context: ..
      dockerfile: docker/cms/Dockerfile
    image: 3dbyte-cms:latest
    restart: unless-stopped
    env_file:
      - ../apps/cms/.env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MEILISEARCH_HOST=http://meilisearch:7700
    volumes:
      - ../apps/cms/config:/opt/apps/cms/config
      - ../apps/cms/src:/opt/apps/cms/src
      - ../apps/cms/package.json:/opt/apps/cms/package.json
      - ../apps/cms/.env:/opt/apps/cms/.env
      - ../apps/cms/public/uploads:/opt/apps/cms/public/uploads
    ports:
      - "1337:1337"
    networks:
      - 3dbyte-network
    depends_on:
      - redis
      - meilisearch

  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.31.0
    container_name: 3dbyte-meilisearch
    command: meilisearch
    environment:
      MEILI_MASTER_KEY: IZKjKX6kXKnH0d4VgL0LrBgSccbImu4PkvDOvL81dww
      MEILI_ENV: development
    volumes:
      - ../apps/cms/docker_volumes/meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - 3dbyte-network

  # Redis
  redis:
    image: redis:8.4.0
    container_name: 3dbyte-redis
    ports:
      - "6379:6379"
    volumes:
      - ../apps/cms/docker_volumes/redis_data:/data
    networks:
      - 3dbyte-network

networks:
  3dbyte-network:
    name: 3dbyte-network
    driver: bridge
